#!/bin/bash

export CABLE_AUX=/home/561/dei561

module purge
module load dot
module load pbs
module load intel-fc/14.3.174
module load intel-cc/14.3.174
#module load openmpi/1.8.8
module load intel-mpi/4.1.1.036
module load netcdf/4.2.1.1

./build.ksh debug

