#!/bin/csh

if(-f $1 ) then
   echo 'gathering depenedencies' 
   echo ''
   if(-f jhtest.f90) then
      rm -f jhtest.f90
   endif
   cat /cs/datastore/u/csdar/srb001/Public/uminclude/UPDEFS $1 >> jhtest.f90
   set incl = /cs/datastore/u/csdar/srb001/Public/uminclude
   ifort -c -fpp -nowarn  -I$incl/common -I$incl/constant  -I$incl/argument  -I$incl/data -I$incl/declaration -I$incl/other jhtest.f90
   if (-f jhtest.o) then
      echo''
      echo 'object file successfully compiled, cleaning up now'       
      echo ''
      rm -f jhtest.o
   endif    
   rm -f jhtest.f90 
else
   echo 'there is no such file'
endif

