
!jhan: review these to put into cable_interface

  ! CABLE-JULES vars to be initialized from file
  ALLOCATE( isnow_flg3l(land_pts, ntiles) )
  error_sum = error_sum + error
  ALLOCATE( snow_rho1l(land_pts, ntiles) )
  error_sum = error_sum + error
  ALLOCATE( snage_tile(land_pts, ntiles) )
  error_sum = error_sum + error

  ALLOCATE( snow_rho1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_rho2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_rho3(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( snow_mass1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_mass2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_mass3(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( snow_depth1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_depth2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_depth3(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( snow_tmp1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_tmp2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( snow_tmp3(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( sthu_tile1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthu_tile2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthu_tile3(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthu_tile4(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthu_tile5(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthu_tile6(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( sthf_tile1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthf_tile2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthf_tile3(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthf_tile4(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthf_tile5(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( sthf_tile6(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( smcl_tile1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( smcl_tile2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( smcl_tile3(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( smcl_tile4(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( smcl_tile5(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( smcl_tile6(land_pts, ntiles ) )
  error_sum = error_sum + error

  ALLOCATE( tsoil_tile1(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( tsoil_tile2(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( tsoil_tile3(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( tsoil_tile4(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( tsoil_tile5(land_pts, ntiles ) )
  error_sum = error_sum + error
  ALLOCATE( tsoil_tile6(land_pts, ntiles ) )
  error_sum = error_sum + error


