!> 
!! Copyright 2017 ARC Centre of Excellence for Climate Systems Science
!!
!! \author  Scott Wales <scott.wales@unimelb.edu.au>
!!
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!! You may obtain a copy of the License at
!!
!!     http://www.apache.org/licenses/LICENSE-2.0
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.

module cable_comms_mod
    use comms_mod, only: comms_t
contains

    SUBROUTINE cable_params_scatter(comm, &
            met,air,ssnow,veg,bgc,soil,canopy, rough,rad,sum_flux,bal, decomp)

        use comms_mod, only: mode_bcast
        use cable_def_types_mod
        use :: cable_mpicommon, only: lpdecomp_t
        USE cable_IO_vars_module, ONLY : landpt, patch
        use cable_input_module, only: allocate_cable_vars
        use mpi_f08
        implicit none
        integer, intent(in) :: comm
        type(lpdecomp_t), optional, intent(in) :: decomp(:)
        TYPE (met_type), intent(inout) :: met
        TYPE (air_type), intent(inout) :: air
        TYPE (soil_snow_type), intent(inout) :: ssnow
        TYPE (veg_parameter_type), intent(inout)  :: veg
        TYPE (bgc_pool_type), intent(inout)  :: bgc
        TYPE (soil_parameter_type), intent(inout) :: soil
        TYPE (canopy_type), intent(inout)    :: canopy
        TYPE (roughness_type), intent(inout) :: rough
        TYPE (radiation_type),intent(inout)  :: rad
        TYPE (sum_flux_type), intent(inout)  :: sum_flux
        TYPE (balances_type), intent(inout)  :: bal
        TYPE (comms_t) :: comms
        integer :: rank

        call MPI_Comm_rank(MPI_Comm(comm), rank)

        if (rank /= 0) then
            ! Allocate arrays, mland and mp are global vars
            allocate(landpt(mland))
            CALL allocate_cable_vars(air,bgc,canopy,met,bal,rad,rough,soil,ssnow, &
                sum_flux,veg,mp)
        end if

        call comms%init(comm, decomp)
        call comms%register_field('landpt',landpt)
        call comms%register_field('patch',patch)

        call comms%register_field('met%ca', met%ca)
        call comms%register_field('met%year', met%year)
        call comms%register_field('met%moy', met%moy)
        call comms%register_field('met%doy', met%doy)
        call comms%register_field('met%hod', met%hod)
        call comms%register_field('met%fsd', met%fsd)
        call comms%register_field('met%fld', met%fld)
        call comms%register_field('met%precip', met%precip)
        call comms%register_field('met%precip_sn', met%precip_sn)
        call comms%register_field('met%tk', met%tk)
        call comms%register_field('met%tvair', met%tvair)
        call comms%register_field('met%tvrad', met%tvrad)
        call comms%register_field('met%pmb', met%pmb)
        call comms%register_field('met%ua', met%ua)
        call comms%register_field('met%qv', met%qv)
        call comms%register_field('met%qvair', met%qvair)
        call comms%register_field('met%da', met%da)
        call comms%register_field('met%dva', met%dva)
        call comms%register_field('met%coszen', met%coszen)
        call comms%register_field('air%rho', air%rho)
        call comms%register_field('air%volm', air%volm)
        call comms%register_field('air%rlam', air%rlam)
        call comms%register_field('air%qsat', air%qsat)
        call comms%register_field('air%epsi', air%epsi)
        call comms%register_field('air%visc', air%visc)
        call comms%register_field('air%psyc', air%psyc)
        call comms%register_field('air%dsatdk', air%dsatdk)
        call comms%register_field('air%cmolar', air%cmolar)
        call comms%register_field('ssnow%dtmlt', ssnow%dtmlt)
        call comms%register_field('ssnow%pudsto', ssnow%pudsto)
        call comms%register_field('ssnow%pudsmx', ssnow%pudsmx)
        call comms%register_field('ssnow%albsoilsn', ssnow%albsoilsn)
        call comms%register_field('ssnow%cls', ssnow%cls)
        call comms%register_field('ssnow%dfn_dtg', ssnow%dfn_dtg)
        call comms%register_field('ssnow%dfh_dtg', ssnow%dfh_dtg)
        call comms%register_field('ssnow%dfe_ddq', ssnow%dfe_ddq)
        call comms%register_field('ssnow%ddq_dtg', ssnow%ddq_dtg)
        call comms%register_field('ssnow%evapsn', ssnow%evapsn)
        call comms%register_field('ssnow%fwtop', ssnow%fwtop)
        call comms%register_field('ssnow%fwtop1', ssnow%fwtop1)
        call comms%register_field('ssnow%fwtop2', ssnow%fwtop2)
        call comms%register_field('ssnow%fwtop3', ssnow%fwtop3)
        call comms%register_field('ssnow%gammzz', ssnow%gammzz)
        call comms%register_field('ssnow%isflag', ssnow%isflag)
        call comms%register_field('ssnow%osnowd', ssnow%osnowd)
        call comms%register_field('ssnow%potev', ssnow%potev)
        call comms%register_field('soil%pwb_min', soil%pwb_min)
        call comms%register_field('ssnow%runoff', ssnow%runoff)
        call comms%register_field('ssnow%rnof1', ssnow%rnof1)
        call comms%register_field('ssnow%rnof2', ssnow%rnof2)
        call comms%register_field('ssnow%rtsoil', ssnow%rtsoil)
        call comms%register_field('ssnow%sconds', ssnow%sconds)
        call comms%register_field('ssnow%sdepth', ssnow%sdepth)
        call comms%register_field('ssnow%smass', ssnow%smass)
        call comms%register_field('ssnow%snage', ssnow%snage)
        call comms%register_field('ssnow%snowd', ssnow%snowd)
        call comms%register_field('ssnow%smelt', ssnow%smelt)
        call comms%register_field('ssnow%ssdn', ssnow%ssdn)
        call comms%register_field('ssnow%ssdnn', ssnow%ssdnn)
        call comms%register_field('ssnow%tgg', ssnow%tgg)
        call comms%register_field('ssnow%tggsn', ssnow%tggsn)
        call comms%register_field('ssnow%tss', ssnow%tss)
        call comms%register_field('ssnow%wb', ssnow%wb)
        call comms%register_field('ssnow%wbfice', ssnow%wbfice)
        call comms%register_field('ssnow%wbice', ssnow%wbice)
        call comms%register_field('ssnow%wblf', ssnow%wblf)
        call comms%register_field('ssnow%S', ssnow%S)
        call comms%register_field('ssnow%Tsoil', ssnow%Tsoil)
        call comms%register_field('ssnow%thetai', ssnow%thetai)
        call comms%register_field('ssnow%snowliq', ssnow%snowliq)
        call comms%register_field('ssnow%Tsurface', ssnow%Tsurface)
        call comms%register_field('ssnow%h0', ssnow%h0)
        call comms%register_field('ssnow%nsnow', ssnow%nsnow)
        call comms%register_field('ssnow%wbtot', ssnow%wbtot)
        call comms%register_field('ssnow%wb_lake', ssnow%wb_lake)
        call comms%register_field('ssnow%sinfil', ssnow%sinfil)
        call comms%register_field('ssnow%evapfbl', ssnow%evapfbl)
        call comms%register_field('ssnow%qstss', ssnow%qstss)
        call comms%register_field('ssnow%wetfac', ssnow%wetfac)
        call comms%register_field('ssnow%owetfac', ssnow%owetfac)
        call comms%register_field('ssnow%t_snwlr', ssnow%t_snwlr)
        call comms%register_field('ssnow%tggav', ssnow%tggav)
        call comms%register_field('ssnow%otss', ssnow%otss)
        call comms%register_field('ssnow%otss_0', ssnow%otss_0)
        call comms%register_field('veg%canst1', veg%canst1)
        call comms%register_field('veg%dleaf', veg%dleaf)
        call comms%register_field('veg%ejmax', veg%ejmax)
        call comms%register_field('veg%frac4', veg%frac4)
        call comms%register_field('veg%froot', veg%froot)
        call comms%register_field('veg%hc', veg%hc)
        call comms%register_field('veg%iveg', veg%iveg)
        call comms%register_field('veg%meth', veg%meth)
        call comms%register_field('veg%rp20', veg%rp20)
        call comms%register_field('veg%rpcoef', veg%rpcoef)
        call comms%register_field('veg%shelrb', veg%shelrb)
        call comms%register_field('veg%wai', veg%wai)
        call comms%register_field('veg%vegcf', veg%vegcf)
        call comms%register_field('veg%tminvj', veg%tminvj)
        call comms%register_field('veg%tmaxvj', veg%tmaxvj)
        call comms%register_field('veg%vbeta', veg%vbeta)
        call comms%register_field('veg%xalbnir', veg%xalbnir)
        call comms%register_field('veg%vcmax', veg%vcmax)
        call comms%register_field('veg%xfang', veg%xfang)
        call comms%register_field('veg%extkn', veg%extkn)
        call comms%register_field('veg%deciduous', veg%deciduous)
        call comms%register_field('veg%a1gs', veg%a1gs)
        call comms%register_field('veg%d0gs', veg%d0gs)
        call comms%register_field('veg%alpha', veg%alpha)
        call comms%register_field('veg%convex', veg%convex)
        call comms%register_field('veg%cfrd', veg%cfrd)
        call comms%register_field('veg%gswmin', veg%gswmin)
        call comms%register_field('veg%conkc0', veg%conkc0)
        call comms%register_field('veg%conko0', veg%conko0)
        call comms%register_field('veg%ekc', veg%ekc)
        call comms%register_field('veg%eko', veg%eko)
        call comms%register_field('veg%clitt', veg%clitt)
        call comms%register_field('veg%zr', veg%zr)
        call comms%register_field('veg%gamma', veg%gamma)
         call comms%register_field('veg%refl', veg%refl)
         call comms%register_field('veg%taul', veg%taul)
         call comms%register_field('veg%disturbance_interval', veg%disturbance_interval)
         call comms%register_field('veg%disturbance_intensity', veg%disturbance_intensity)
         call comms%register_field('veg%g0', veg%g0)
         call comms%register_field('veg%g1', veg%g1)
         call comms%register_field('bgc%cplant', bgc%cplant)
         call comms%register_field('bgc%csoil', bgc%csoil)
         call comms%register_field('bgc%ratecp', bgc%ratecp, mode=mode_bcast)
         call comms%register_field('bgc%ratecs', bgc%ratecs, mode=mode_bcast)
         call comms%register_field('soil%albsoil', soil%albsoil)
         call comms%register_field('soil%bch', soil%bch)
         call comms%register_field('soil%c3', soil%c3)
         call comms%register_field('soil%clay', soil%clay)
         call comms%register_field('soil%cnsd', soil%cnsd)
         call comms%register_field('soil%css', soil%css)
         call comms%register_field('soil%hsbh', soil%hsbh)
         call comms%register_field('soil%hyds', soil%hyds)
         call comms%register_field('soil%i2bp3', soil%i2bp3)
         call comms%register_field('soil%ibp2', soil%ibp2)
         call comms%register_field('soil%isoilm', soil%isoilm)
         call comms%register_field('soil%rhosoil', soil%rhosoil)
         call comms%register_field('veg%rs20', veg%rs20)
         call comms%register_field('soil%sand', soil%sand)
         call comms%register_field('soil%sfc', soil%sfc)
         call comms%register_field('soil%silt', soil%silt)
         call comms%register_field('soil%ssat', soil%ssat)
         call comms%register_field('soil%sucs', soil%sucs)
         call comms%register_field('soil%swilt', soil%swilt)
         call comms%register_field('soil%zeta', soil%zeta)
         call comms%register_field('soil%fsatmax', soil%fsatmax)
         call comms%register_field('soil%zse', soil%zse, mode=mode_bcast)
         call comms%register_field('soil%zshh', soil%zshh, mode=mode_bcast)
         call comms%register_field('soil%soilcol', soil%soilcol)
         call comms%register_field('canopy%fess', canopy%fess)
         call comms%register_field('canopy%fesp', canopy%fesp)
         call comms%register_field('canopy%cansto', canopy%cansto)
         call comms%register_field('canopy%oldcansto', canopy%oldcansto)
         call comms%register_field('canopy%cduv', canopy%cduv)
         call comms%register_field('canopy%delwc', canopy%delwc)
         call comms%register_field('canopy%dewmm', canopy%dewmm)
         call comms%register_field('canopy%dgdtg', canopy%dgdtg)
         call comms%register_field('canopy%fe', canopy%fe)
         call comms%register_field('canopy%fh', canopy%fh)
         call comms%register_field('canopy%fpn', canopy%fpn)
         call comms%register_field('canopy%frp', canopy%frp)
         call comms%register_field('canopy%frpw', canopy%frpw)
         call comms%register_field('canopy%frpr', canopy%frpr)
         call comms%register_field('canopy%frs', canopy%frs)
         call comms%register_field('canopy%fnee', canopy%fnee)
         call comms%register_field('canopy%frday', canopy%frday)
         call comms%register_field('canopy%fnv', canopy%fnv)
         call comms%register_field('canopy%fev', canopy%fev)
         call comms%register_field('canopy%fevc', canopy%fevc)
         call comms%register_field('canopy%fevw', canopy%fevw)
         call comms%register_field('canopy%fhv', canopy%fhv)
         call comms%register_field('canopy%fhvw', canopy%fhvw)
         call comms%register_field('canopy%fns', canopy%fns)
         call comms%register_field('canopy%fes', canopy%fes)
         call comms%register_field('canopy%fhs', canopy%fhs)
         call comms%register_field('canopy%fwet', canopy%fwet)
         call comms%register_field('canopy%ga', canopy%ga)
         call comms%register_field('canopy%ghflux', canopy%ghflux)
         call comms%register_field('canopy%precis', canopy%precis)
         call comms%register_field('canopy%qscrn', canopy%qscrn)
         call comms%register_field('canopy%rnet', canopy%rnet)
         call comms%register_field('canopy%segg', canopy%segg)
         call comms%register_field('canopy%sghflux', canopy%sghflux)
         call comms%register_field('canopy%spill', canopy%spill)
         call comms%register_field('canopy%through', canopy%through)
         call comms%register_field('canopy%tscrn', canopy%tscrn)
         call comms%register_field('canopy%tv', canopy%tv)
         call comms%register_field('canopy%us', canopy%us)
         call comms%register_field('canopy%uscrn', canopy%uscrn)
         call comms%register_field('canopy%vlaiw', canopy%vlaiw)
         call comms%register_field('canopy%rghlai', canopy%rghlai)
         call comms%register_field('canopy%wcint', canopy%wcint)
         call comms%register_field('canopy%evapfbl', canopy%evapfbl)
         call comms%register_field('canopy%epot', canopy%epot)
         call comms%register_field('canopy%fnpp', canopy%fnpp)
         call comms%register_field('canopy%fevw_pot', canopy%fevw_pot)
         call comms%register_field('canopy%gswx_T', canopy%gswx_T)
         call comms%register_field('canopy%cdtq', canopy%cdtq)
         call comms%register_field('canopy%wetfac_cs', canopy%wetfac_cs)
         call comms%register_field('canopy%fwsoil', canopy%fwsoil)
         call comms%register_field('canopy%gswx', canopy%gswx)
         call comms%register_field('canopy%zetar', canopy%zetar)
         call comms%register_field('rough%coexp', rough%coexp)
         call comms%register_field('rough%disp', rough%disp)
         call comms%register_field('rough%hruff', rough%hruff)
         call comms%register_field('rough%hruff_grmx', rough%hruff_grmx)
         call comms%register_field('rough%rt0us', rough%rt0us)
         call comms%register_field('rough%rt1usa', rough%rt1usa)
         call comms%register_field('rough%rt1usb', rough%rt1usb)
         call comms%register_field('rough%rt1', rough%rt1)
         call comms%register_field('rough%term2', rough%term2)
         call comms%register_field('rough%term3', rough%term3)
         call comms%register_field('rough%term5', rough%term5)
         call comms%register_field('rough%term6', rough%term6)
         call comms%register_field('rough%usuh', rough%usuh)
         call comms%register_field('rough%za_uv', rough%za_uv)
         call comms%register_field('rough%za_tq', rough%za_tq)
         call comms%register_field('rough%z0m', rough%z0m)
         call comms%register_field('rough%zref_uv', rough%zref_uv)
         call comms%register_field('rough%zref_tq', rough%zref_tq)
         call comms%register_field('rough%zruffs', rough%zruffs)
         call comms%register_field('rough%z0soilsn', rough%z0soilsn)
         call comms%register_field('rough%z0soil', rough%z0soil)
         call comms%register_field('rad%albedo', rad%albedo)
         call comms%register_field('rad%extkb', rad%extkb)
         call comms%register_field('rad%extkd2', rad%extkd2)
         call comms%register_field('rad%extkd', rad%extkd)
         call comms%register_field('rad%flws', rad%flws)
         call comms%register_field('rad%fvlai', rad%fvlai)
         call comms%register_field('rad%gradis', rad%gradis)
         call comms%register_field('rad%latitude', rad%latitude)
         call comms%register_field('rad%lwabv', rad%lwabv)
         call comms%register_field('rad%qcan', rad%qcan)
         call comms%register_field('rad%qssabs', rad%qssabs)
         call comms%register_field('rad%rhocdf', rad%rhocdf)
         call comms%register_field('rad%rniso', rad%rniso)
         call comms%register_field('rad%scalex', rad%scalex)
         call comms%register_field('rad%transd', rad%transd)
         call comms%register_field('rad%trad', rad%trad)
         call comms%register_field('rad%reffdf', rad%reffdf)
         call comms%register_field('rad%reffbm', rad%reffbm)
         call comms%register_field('rad%extkbm', rad%extkbm)
         call comms%register_field('rad%extkdm', rad%extkdm)
         call comms%register_field('rad%fbeam', rad%fbeam)
         call comms%register_field('rad%cexpkbm', rad%cexpkbm)
         call comms%register_field('rad%cexpkdm', rad%cexpkdm)
         call comms%register_field('rad%rhocbm', rad%rhocbm)
         call comms%register_field('rad%transb', rad%transb)
         call comms%register_field('sum_flux%sumpn', sum_flux%sumpn)
         call comms%register_field('sum_flux%sumrp', sum_flux%sumrp)
         call comms%register_field('sum_flux%sumrpw', sum_flux%sumrpw)
         call comms%register_field('sum_flux%sumrpr', sum_flux%sumrpr)
         call comms%register_field('sum_flux%sumrs', sum_flux%sumrs)
         call comms%register_field('sum_flux%sumrd', sum_flux%sumrd)
         call comms%register_field('sum_flux%dsumpn', sum_flux%dsumpn)
         call comms%register_field('sum_flux%dsumrp', sum_flux%dsumrp)
         call comms%register_field('sum_flux%dsumrs', sum_flux%dsumrs)
         call comms%register_field('sum_flux%dsumrd', sum_flux%dsumrd)
         call comms%register_field('sum_flux%sumxrp', sum_flux%sumxrp)
         call comms%register_field('sum_flux%sumxrs', sum_flux%sumxrs)
         call comms%register_field('bal%drybal', bal%drybal)
         call comms%register_field('bal%ebal', bal%ebal)
         call comms%register_field('bal%ebal_tot', bal%ebal_tot)
         call comms%register_field('bal%ebal_cncheck', bal%ebal_cncheck)
         call comms%register_field('bal%ebal_tot_cncheck', bal%ebal_tot_cncheck)
         call comms%register_field('bal%evap_tot', bal%evap_tot)
         call comms%register_field('bal%osnowd0', bal%osnowd0)
         call comms%register_field('bal%precip_tot', bal%precip_tot)
         call comms%register_field('bal%rnoff_tot', bal%rnoff_tot)
         call comms%register_field('bal%wbal', bal%wbal)
         call comms%register_field('bal%wbal_tot', bal%wbal_tot)
         call comms%register_field('bal%wbtot0', bal%wbtot0)
         call comms%register_field('bal%wetbal', bal%wetbal)
         call comms%register_field('bal%owbtot', bal%owbtot)
         call comms%register_field('bal%evapc_tot', bal%evapc_tot)
         call comms%register_field('bal%evaps_tot', bal%evaps_tot)
         call comms%register_field('bal%rnof1_tot', bal%rnof1_tot)
         call comms%register_field('bal%rnof2_tot', bal%rnof2_tot)
         call comms%register_field('bal%snowdc_tot', bal%snowdc_tot)
         call comms%register_field('bal%wbal_tot1', bal%wbal_tot1)
         call comms%register_field('bal%delwc_tot', bal%delwc_tot)
         call comms%register_field('bal%qasrf_tot', bal%qasrf_tot)
         call comms%register_field('bal%qfsrf_tot', bal%qfsrf_tot)
         call comms%register_field('bal%qssrf_tot', bal%qssrf_tot)
         call comms%register_field('bal%ebaltr', bal%ebaltr)
         call comms%register_field('bal%ebal_tottr', bal%ebal_tottr)
         call comms%register_field('bal%cansto0', bal%cansto0)
         call comms%register_field('ssnow%iantrct', ssnow%iantrct)
         call comms%register_field('ssnow%tss_p', ssnow%tss_p)
         call comms%register_field('ssnow%deltss', ssnow%deltss)
         call comms%register_field('ssnow%owb1', ssnow%owb1)
         call comms%register_field('ssnow%wbtot1', ssnow%wbtot1)
         call comms%register_field('ssnow%tprecip', ssnow%tprecip)
         call comms%register_field('ssnow%tevap', ssnow%tevap)
         call comms%register_field('ssnow%trnoff', ssnow%trnoff)
         call comms%register_field('ssnow%totenbal', ssnow%totenbal)
         call comms%register_field('ssnow%totenbal2', ssnow%totenbal2)
         call comms%register_field('ssnow%fland', ssnow%fland)
         call comms%register_field('ssnow%ifland', ssnow%ifland)
         call comms%register_field('ssnow%tilefrac', ssnow%tilefrac)
         call comms%register_field('ssnow%qasrf', ssnow%qasrf)
         call comms%register_field('ssnow%qfsrf', ssnow%qfsrf)
         call comms%register_field('ssnow%qssrf', ssnow%qssrf)
         call comms%register_field('veg%vlaimax', veg%vlaimax)
         call comms%register_field('rad%albedo_T', rad%albedo_T)
         call comms%register_field('rad%longitude', rad%longitude)

        call comms%scatter()
        call comms%free()
    END SUBROUTINE

    SUBROUTINE intypes_register(comm, met, veg, intypes, decomp)
        use comms_mod, only: comms_t
        use cable_def_types_mod, only: met_type, veg_parameter_type
        use cable_mpicommon, only: lpdecomp_t
        implicit none
        integer, intent(in) :: comm
        type(lpdecomp_t), optional, intent(in) :: decomp(:)
        type(met_type), intent(inout) :: met
        type(veg_parameter_type), intent(inout) :: veg
        type(comms_t), intent(out) :: intypes

        call intypes%init(comm, decomp)
        call intypes%register_field('met%fsd', met%fsd)
        call intypes%register_field('met%tk', met%tk)
        call intypes%register_field('met%pmb', met%pmb)
        call intypes%register_field('met%qv', met%qv)
        call intypes%register_field('met%ua', met%ua)
        call intypes%register_field('met%precip', met%precip)
        call intypes%register_field('met%precip_sn', met%precip_sn)
        call intypes%register_field('met%fld', met%fld)
        call intypes%register_field('met%ca', met%ca)
        call intypes%register_field('met%coszen', met%coszen)
        call intypes%register_field('met%Ndep', met%Ndep)
        call intypes%register_field('veg%vlai', veg%vlai)
        call intypes%register_field('met%year', met%year)
        call intypes%register_field('met%moy', met%moy)
        call intypes%register_field('met%doy', met%doy)
        call intypes%register_field('met%hod', met%hod)
    END SUBROUTINE

    SUBROUTINE outtypes_register(comm,met,canopy,ssnow,rad,bal,air,soil,veg, outtypes, decomp)
        USE cable_def_types_mod
        use :: cable_mpicommon, only: lpdecomp_t

        IMPLICIT NONE

        INTEGER :: comm ! MPI communicator to talk to the workers

        TYPE(met_type), INTENT(IN) :: met
        TYPE(canopy_type), INTENT(IN) :: canopy
        TYPE(soil_snow_type), INTENT(IN) :: ssnow
        TYPE(radiation_type), INTENT(IN) :: rad
        TYPE (balances_type),INTENT(INOUT):: bal 
        TYPE (air_type),INTENT(IN)     :: air
        TYPE (soil_parameter_type),INTENT(IN) :: soil ! soil parameters
        TYPE (veg_parameter_type),INTENT(IN) :: veg ! vegetation parameters
        type(lpdecomp_t), optional, intent(in) :: decomp(:)
        type(comms_t), intent(out) :: outtypes

        call outtypes%init(comm, decomp)
        call outtypes%register_field('rad%qcan', rad%qcan)
        call outtypes%register_field('met%fsd', met%fsd)
        call outtypes%register_field('canopy%evapfbl', canopy%evapfbl)
        call outtypes%register_field('canopy%gswx', canopy%gswx)
        call outtypes%register_field('canopy%zetar', canopy%zetar)
        call outtypes%register_field('ssnow%dtmlt', ssnow%dtmlt)
        call outtypes%register_field('ssnow%albsoilsn', ssnow%albsoilsn)
        call outtypes%register_field('ssnow%gammzz', ssnow%gammzz)
        call outtypes%register_field('ssnow%sconds', ssnow%sconds)
        call outtypes%register_field('ssnow%sdepth', ssnow%sdepth)
        call outtypes%register_field('ssnow%smass', ssnow%smass)
        call outtypes%register_field('ssnow%ssdn', ssnow%ssdn)
        call outtypes%register_field('ssnow%tgg', ssnow%tgg)
        call outtypes%register_field('ssnow%tggsn', ssnow%tggsn)
        call outtypes%register_field('ssnow%wb', ssnow%wb)
        call outtypes%register_field('ssnow%evapfbl', ssnow%evapfbl)
        call outtypes%register_field('ssnow%wbfice', ssnow%wbfice)
        call outtypes%register_field('ssnow%wbice', ssnow%wbice)
        call outtypes%register_field('ssnow%wblf', ssnow%wblf)
        call outtypes%register_field('ssnow%S', ssnow%S)
        call outtypes%register_field('ssnow%Tsoil', ssnow%Tsoil)
        call outtypes%register_field('ssnow%thetai', ssnow%thetai)
        call outtypes%register_field('ssnow%snowliq', ssnow%snowliq)
        call outtypes%register_field('rad%fbeam', rad%fbeam)
        call outtypes%register_field('rad%albedo', rad%albedo)
        call outtypes%register_field('rad%fvlai', rad%fvlai)
        call outtypes%register_field('rad%gradis', rad%gradis)
        call outtypes%register_field('rad%rhocdf', rad%rhocdf)
        call outtypes%register_field('rad%rniso', rad%rniso)
        call outtypes%register_field('rad%scalex', rad%scalex)
        call outtypes%register_field('rad%reffdf', rad%reffdf)
        call outtypes%register_field('rad%reffbm', rad%reffbm)
        call outtypes%register_field('rad%extkbm', rad%extkbm)
        call outtypes%register_field('rad%extkdm', rad%extkdm)
        call outtypes%register_field('rad%cexpkbm', rad%cexpkbm)
        call outtypes%register_field('rad%cexpkdm', rad%cexpkdm)
        call outtypes%register_field('rad%rhocbm', rad%rhocbm)
        call outtypes%register_field('soil%albsoil', soil%albsoil)
        call outtypes%register_field('veg%refl', veg%refl)
        call outtypes%register_field('veg%taul', veg%taul)
        call outtypes%register_field('veg%froot', veg%froot)
        call outtypes%register_field('met%ca', met%ca)
        call outtypes%register_field('met%fld', met%fld)
        call outtypes%register_field('met%precip', met%precip)
        call outtypes%register_field('met%precip_sn', met%precip_sn)
        call outtypes%register_field('met%tk', met%tk)
        call outtypes%register_field('met%tvair', met%tvair)
        call outtypes%register_field('met%tvrad', met%tvrad)
        call outtypes%register_field('met%pmb', met%pmb)
        call outtypes%register_field('met%ua', met%ua)
        call outtypes%register_field('met%qv', met%qv)
        call outtypes%register_field('met%qvair', met%qvair)
        call outtypes%register_field('met%da', met%da)
        call outtypes%register_field('met%dva', met%dva)
        call outtypes%register_field('met%coszen', met%coszen)
        call outtypes%register_field('canopy%fess', canopy%fess)
        call outtypes%register_field('canopy%fesp', canopy%fesp)
        call outtypes%register_field('canopy%cansto', canopy%cansto)
        call outtypes%register_field('canopy%cduv', canopy%cduv)
        call outtypes%register_field('canopy%delwc', canopy%delwc)
        call outtypes%register_field('canopy%dewmm', canopy%dewmm)
        call outtypes%register_field('canopy%dgdtg', canopy%dgdtg)
        call outtypes%register_field('canopy%fe', canopy%fe)
        call outtypes%register_field('canopy%fh', canopy%fh)
        call outtypes%register_field('canopy%fpn', canopy%fpn)
        call outtypes%register_field('canopy%frp', canopy%frp)
        call outtypes%register_field('canopy%frpw', canopy%frpw)
        call outtypes%register_field('canopy%frpr', canopy%frpr)
        call outtypes%register_field('canopy%frs', canopy%frs)
        call outtypes%register_field('canopy%fnee', canopy%fnee)
        call outtypes%register_field('canopy%frday', canopy%frday)
        call outtypes%register_field('canopy%fnv', canopy%fnv)
        call outtypes%register_field('canopy%fev', canopy%fev)
        call outtypes%register_field('canopy%fevc', canopy%fevc)
        call outtypes%register_field('canopy%fevw', canopy%fevw)
        call outtypes%register_field('canopy%fhv', canopy%fhv)
        call outtypes%register_field('canopy%fhvw', canopy%fhvw)
        call outtypes%register_field('canopy%fns', canopy%fns)
        call outtypes%register_field('canopy%fes', canopy%fes)
        call outtypes%register_field('canopy%fes_cor', canopy%fes_cor)
        call outtypes%register_field('canopy%fhs', canopy%fhs)
        call outtypes%register_field('canopy%fhs_cor', canopy%fhs_cor)
        call outtypes%register_field('canopy%fwet', canopy%fwet)
        call outtypes%register_field('canopy%epot', canopy%epot)
        call outtypes%register_field('canopy%fnpp', canopy%fnpp)
        call outtypes%register_field('canopy%fevw_pot', canopy%fevw_pot)
        call outtypes%register_field('canopy%gswx_T', canopy%gswx_T)
        call outtypes%register_field('canopy%cdtq', canopy%cdtq)
        call outtypes%register_field('canopy%wetfac_cs', canopy%wetfac_cs)
        call outtypes%register_field('canopy%ga', canopy%ga)
        call outtypes%register_field('canopy%ghflux', canopy%ghflux)
        call outtypes%register_field('canopy%precis', canopy%precis)
        call outtypes%register_field('canopy%qscrn', canopy%qscrn)
        call outtypes%register_field('canopy%rnet', canopy%rnet)
        call outtypes%register_field('canopy%segg', canopy%segg)
        call outtypes%register_field('canopy%sghflux', canopy%sghflux)
        call outtypes%register_field('canopy%spill', canopy%spill)
        call outtypes%register_field('canopy%through', canopy%through)
        call outtypes%register_field('canopy%tscrn', canopy%tscrn)
        call outtypes%register_field('canopy%tv', canopy%tv)
        call outtypes%register_field('canopy%us', canopy%us)
        call outtypes%register_field('canopy%uscrn', canopy%uscrn)
        call outtypes%register_field('canopy%vlaiw', canopy%vlaiw)
        call outtypes%register_field('canopy%rghlai', canopy%rghlai)
        call outtypes%register_field('canopy%wcint', canopy%wcint)
        call outtypes%register_field('canopy%fwsoil', canopy%fwsoil)
        call outtypes%register_field('ssnow%pudsto', ssnow%pudsto)
        call outtypes%register_field('ssnow%pudsmx', ssnow%pudsmx)
        call outtypes%register_field('ssnow%cls', ssnow%cls)
        call outtypes%register_field('ssnow%dfn_dtg', ssnow%dfn_dtg)
        call outtypes%register_field('ssnow%dfh_dtg', ssnow%dfh_dtg)
        call outtypes%register_field('ssnow%dfe_ddq', ssnow%dfe_ddq)
        call outtypes%register_field('ssnow%ddq_dtg', ssnow%ddq_dtg)
        call outtypes%register_field('ssnow%evapsn', ssnow%evapsn)
        call outtypes%register_field('ssnow%fwtop', ssnow%fwtop)
        call outtypes%register_field('ssnow%fwtop1', ssnow%fwtop1)
        call outtypes%register_field('ssnow%fwtop2', ssnow%fwtop2)
        call outtypes%register_field('ssnow%fwtop3', ssnow%fwtop3)
        call outtypes%register_field('ssnow%isflag', ssnow%isflag)
        call outtypes%register_field('ssnow%osnowd', ssnow%osnowd)
        call outtypes%register_field('ssnow%potev', ssnow%potev)
        call outtypes%register_field('soil%pwb_min', soil%pwb_min)
        call outtypes%register_field('ssnow%runoff', ssnow%runoff)
        call outtypes%register_field('ssnow%rnof1', ssnow%rnof1)
        call outtypes%register_field('ssnow%rnof2', ssnow%rnof2)
        call outtypes%register_field('ssnow%rtsoil', ssnow%rtsoil)
        call outtypes%register_field('ssnow%snage', ssnow%snage)
        call outtypes%register_field('ssnow%snowd', ssnow%snowd)
        call outtypes%register_field('ssnow%smelt', ssnow%smelt)
        call outtypes%register_field('ssnow%ssdnn', ssnow%ssdnn)
        call outtypes%register_field('ssnow%tss', ssnow%tss)
        call outtypes%register_field('ssnow%wbtot', ssnow%wbtot)
        call outtypes%register_field('ssnow%wb_lake', ssnow%wb_lake)
        call outtypes%register_field('ssnow%sinfil', ssnow%sinfil)
        call outtypes%register_field('ssnow%qstss', ssnow%qstss)
        call outtypes%register_field('ssnow%wetfac', ssnow%wetfac)
        call outtypes%register_field('ssnow%owetfac', ssnow%owetfac)
        call outtypes%register_field('ssnow%t_snwlr', ssnow%t_snwlr)
        call outtypes%register_field('ssnow%tggav', ssnow%tggav)
        call outtypes%register_field('ssnow%otss', ssnow%otss)
        call outtypes%register_field('ssnow%otss_0', ssnow%otss_0)
        call outtypes%register_field('rad%extkb', rad%extkb)
        call outtypes%register_field('rad%extkd2', rad%extkd2)
        call outtypes%register_field('rad%extkd', rad%extkd)
        call outtypes%register_field('rad%flws', rad%flws)
        call outtypes%register_field('rad%latitude', rad%latitude)
        call outtypes%register_field('rad%lwabv', rad%lwabv)
        call outtypes%register_field('rad%qssabs', rad%qssabs)
        call outtypes%register_field('rad%transd', rad%transd)
        call outtypes%register_field('rad%trad', rad%trad)
        call outtypes%register_field('rad%transb', rad%transb)
        call outtypes%register_field('bal%drybal', bal%drybal)
        call outtypes%register_field('bal%osnowd0', bal%osnowd0)
        call outtypes%register_field('bal%wbtot0', bal%wbtot0)
        call outtypes%register_field('bal%wetbal', bal%wetbal)
        call outtypes%register_field('air%rho', air%rho)
        call outtypes%register_field('air%volm', air%volm)
        call outtypes%register_field('air%rlam', air%rlam)
        call outtypes%register_field('air%qsat', air%qsat)
        call outtypes%register_field('air%epsi', air%epsi)
        call outtypes%register_field('air%visc', air%visc)
        call outtypes%register_field('air%psyc', air%psyc)
        call outtypes%register_field('air%dsatdk', air%dsatdk)
        call outtypes%register_field('air%cmolar', air%cmolar)
        call outtypes%register_field('soil%bch', soil%bch)
        call outtypes%register_field('soil%c3', soil%c3)
        call outtypes%register_field('soil%clay', soil%clay)
        call outtypes%register_field('soil%cnsd', soil%cnsd)
        call outtypes%register_field('soil%css', soil%css)
        call outtypes%register_field('soil%hsbh', soil%hsbh)
        call outtypes%register_field('soil%hyds', soil%hyds)
        call outtypes%register_field('soil%i2bp3', soil%i2bp3)
        call outtypes%register_field('soil%ibp2', soil%ibp2)
        call outtypes%register_field('soil%isoilm', soil%isoilm)
        call outtypes%register_field('soil%rhosoil', soil%rhosoil)
        call outtypes%register_field('veg%rs20', veg%rs20)
        call outtypes%register_field('soil%sand', soil%sand)
        call outtypes%register_field('soil%sfc', soil%sfc)
        call outtypes%register_field('soil%silt', soil%silt)
        call outtypes%register_field('soil%ssat', soil%ssat)
        call outtypes%register_field('soil%sucs', soil%sucs)
        call outtypes%register_field('soil%swilt', soil%swilt)
        call outtypes%register_field('veg%iveg', veg%iveg)
        call outtypes%register_field('veg%meth', veg%meth)
        call outtypes%register_field('veg%vlai', veg%vlai)
        call outtypes%register_field('veg%canst1', veg%canst1)
        call outtypes%register_field('veg%ejmax', veg%ejmax)
        call outtypes%register_field('veg%frac4', veg%frac4)
        call outtypes%register_field('veg%wai', veg%wai)
        call outtypes%register_field('veg%vegcf', veg%vegcf)
        call outtypes%register_field('veg%tminvj', veg%tminvj)
        call outtypes%register_field('veg%tmaxvj', veg%tmaxvj)
        call outtypes%register_field('veg%vbeta', veg%vbeta)
        call outtypes%register_field('veg%xalbnir', veg%xalbnir)
        call outtypes%register_field('veg%hc', veg%hc)
        call outtypes%register_field('veg%shelrb', veg%shelrb)
        call outtypes%register_field('veg%vcmax', veg%vcmax)
        call outtypes%register_field('veg%xfang', veg%xfang)
        call outtypes%register_field('veg%dleaf', veg%dleaf)
        call outtypes%register_field('veg%rp20', veg%rp20)
        call outtypes%register_field('veg%rpcoef', veg%rpcoef)
        call outtypes%register_field('veg%extkn', veg%extkn)
        call outtypes%register_field('veg%deciduous', veg%deciduous)
        call outtypes%register_field('ssnow%Tsurface', ssnow%Tsurface)
        call outtypes%register_field('ssnow%h0', ssnow%h0)
        call outtypes%register_field('ssnow%delwcol', ssnow%delwcol)
        call outtypes%register_field('ssnow%evap', ssnow%evap)
        call outtypes%register_field('ssnow%nsnow', ssnow%nsnow)
        call outtypes%register_field('ssnow%nsteps', ssnow%nsteps)
    end subroutine

    subroutine casa_params_scatter (comm,casabiome,casapool,casaflux,casamet,&
            casabal,phen, decomp)

        USE cable_def_types_mod
        USE casavariable
        USE phenvariable
        use :: cable_mpicommon, only: lpdecomp_t

        INTEGER, INTENT(IN) :: comm  ! MPI communicator
        type(lpdecomp_t), optional, intent(in) :: decomp(:)

        TYPE (casa_biome)   , INTENT(INOUT) :: casabiome
        TYPE (casa_pool)   , INTENT(INOUT) :: casapool
        TYPE (casa_flux)   , INTENT(INOUT) :: casaflux
        TYPE (casa_met)    , INTENT(INOUT) :: casamet
        TYPE (casa_balance), INTENT(INOUT) :: casabal
        TYPE (phen_variable), INTENT(INOUT)  :: phen 
        type(comms_t) :: comms

        IF (.NOT. ASSOCIATED (casabiome%ivt2)) THEN
            WRITE (*,*) 'worker alloc casa and phen var with m patches: ',mp
            CALL alloc_casavariable (casabiome, casapool, &
                &      casaflux, casamet, casabal, mp)
            CALL alloc_phenvariable (phen, mp)
        END IF

        call comms%init(comm, decomp)
        call comms%register_field('casabiome%ivt2', casabiome%ivt2)
        call comms%register_field('casabiome%xkleafcoldmax', casabiome%xkleafcoldmax)
        call comms%register_field('casabiome%xkleafcoldexp', casabiome%xkleafcoldexp)
        call comms%register_field('casabiome%xkleafdrymax', casabiome%xkleafdrymax)
        call comms%register_field('casabiome%xkleafdryexp', casabiome%xkleafdryexp)
        call comms%register_field('casabiome%glaimax', casabiome%glaimax)
        call comms%register_field('casabiome%glaimin', casabiome%glaimin)
        call comms%register_field('casabiome%sla', casabiome%sla)
        call comms%register_field('casabiome%ratiofrootleaf', casabiome%ratiofrootleaf)
        call comms%register_field('casabiome%kroot', casabiome%kroot)
        call comms%register_field('casabiome%krootlen', casabiome%krootlen)
        call comms%register_field('casabiome%rootdepth', casabiome%rootdepth)
        call comms%register_field('casabiome%kuptake', casabiome%kuptake)
        call comms%register_field('casabiome%kminN', casabiome%kminN)
        call comms%register_field('casabiome%KuplabP', casabiome%KuplabP)
        call comms%register_field('casabiome%kclabrate', casabiome%kclabrate)
        call comms%register_field('casabiome%xnpmax', casabiome%xnpmax)
        call comms%register_field('casabiome%q10soil', casabiome%q10soil)
        call comms%register_field('casabiome%xkoptlitter', casabiome%xkoptlitter)
        call comms%register_field('casabiome%xkoptsoil', casabiome%xkoptsoil)
        call comms%register_field('casabiome%maxfinelitter', casabiome%maxfinelitter)
        call comms%register_field('casabiome%maxcwd', casabiome%maxcwd)
        call comms%register_field('casabiome%prodptase', casabiome%prodptase)
        call comms%register_field('casabiome%costnpup', casabiome%costnpup)
        call comms%register_field('casabiome%xkplab', casabiome%xkplab)
        call comms%register_field('casabiome%xkpsorb', casabiome%xkpsorb)
        call comms%register_field('casabiome%xkpocc', casabiome%xkpocc)
        call comms%register_field('casabiome%nintercept', casabiome%nintercept)
        call comms%register_field('casabiome%nslope', casabiome%nslope)
        call comms%register_field('casabiome%plantrate', casabiome%plantrate)
        call comms%register_field('casabiome%rmplant', casabiome%rmplant)
        call comms%register_field('casabiome%fracnpptoP', casabiome%fracnpptoP)
        call comms%register_field('casabiome%fraclignin', casabiome%fraclignin)
        call comms%register_field('casabiome%fraclabile', casabiome%fraclabile)
        call comms%register_field('casabiome%ratioNCplantmin', casabiome%ratioNCplantmin)
        call comms%register_field('casabiome%ratioNCplantmax', casabiome%ratioNCplantmax)
        call comms%register_field('casabiome%ratioPCplantmin', casabiome%ratioPCplantmin)
        call comms%register_field('casabiome%ratioPCplantmax', casabiome%ratioPCplantmax)
        call comms%register_field('casabiome%fracLigninplant', casabiome%fracLigninplant)
        call comms%register_field('casabiome%ftransNPtoL', casabiome%ftransNPtoL)
        call comms%register_field('casabiome%ftransPPtoL', casabiome%ftransPPtoL)
        call comms%register_field('casabiome%litterrate', casabiome%litterrate)
        call comms%register_field('casabiome%soilrate', casabiome%soilrate)
        call comms%register_field('casabiome%ratioNPplantmin', casabiome%ratioNPplantmin)
        call comms%register_field('casabiome%ratioNPplantmax', casabiome%ratioNPplantmax)
        call comms%register_field('casapool%Clabile', casapool%Clabile)
        call comms%register_field('casapool%dClabiledt', casapool%dClabiledt)
        call comms%register_field('casapool%Cplant', casapool%Cplant)
        call comms%register_field('casapool%Nplant', casapool%Nplant)
        call comms%register_field('casapool%Pplant', casapool%Pplant)
        call comms%register_field('casapool%dCplantdt', casapool%dCplantdt)
        call comms%register_field('casapool%dNplantdt', casapool%dNplantdt)
        call comms%register_field('casapool%dPplantdt', casapool%dPplantdt)
        call comms%register_field('casapool%ratioNCplant', casapool%ratioNCplant)
        call comms%register_field('casapool%ratioPCplant', casapool%ratioPCplant)
        call comms%register_field('casapool%Nsoilmin', casapool%Nsoilmin)
        call comms%register_field('casapool%Psoillab', casapool%Psoillab)
        call comms%register_field('casapool%Psoilsorb', casapool%Psoilsorb)
        call comms%register_field('casapool%Psoilocc', casapool%Psoilocc)
        call comms%register_field('casapool%dNsoilmindt', casapool%dNsoilmindt)
        call comms%register_field('casapool%dPsoillabdt', casapool%dPsoillabdt)
        call comms%register_field('casapool%dPsoilsorbdt', casapool%dPsoilsorbdt)
        call comms%register_field('casapool%dPsoiloccdt', casapool%dPsoiloccdt)
        call comms%register_field('casapool%Clitter', casapool%Clitter)
        call comms%register_field('casapool%Nlitter', casapool%Nlitter)
        call comms%register_field('casapool%Plitter', casapool%Plitter)
        call comms%register_field('casapool%dClitterdt', casapool%dClitterdt)
        call comms%register_field('casapool%dNlitterdt', casapool%dNlitterdt)
        call comms%register_field('casapool%dPlitterdt', casapool%dPlitterdt)
        call comms%register_field('casapool%ratioNClitter', casapool%ratioNClitter)
        call comms%register_field('casapool%ratioPClitter', casapool%ratioPClitter)
        call comms%register_field('casapool%Csoil', casapool%Csoil)
        call comms%register_field('casapool%Nsoil', casapool%Nsoil)
        call comms%register_field('casapool%Psoil', casapool%Psoil)
        call comms%register_field('casapool%dCsoildt', casapool%dCsoildt)
        call comms%register_field('casapool%dNsoildt', casapool%dNsoildt)
        call comms%register_field('casapool%dPsoildt', casapool%dPsoildt)
        call comms%register_field('casapool%ratioNCsoil', casapool%ratioNCsoil)
        call comms%register_field('casapool%ratioPCsoil', casapool%ratioPCsoil)
        call comms%register_field('casapool%ratioNCsoilnew', casapool%ratioNCsoilnew)
        call comms%register_field('casapool%ratioNCsoilmin', casapool%ratioNCsoilmin)
        call comms%register_field('casapool%ratioNCsoilmax', casapool%ratioNCsoilmax)
        call comms%register_field('casapool%ratioNPplant', casapool%ratioNPplant)
        call comms%register_field('casapool%ratioNPlitter', casapool%ratioNPlitter)
        call comms%register_field('casapool%ratioNPsoil', casapool%ratioNPsoil)
        call comms%register_field('casaflux%Cgpp', casaflux%Cgpp)
        call comms%register_field('casaflux%Cnpp', casaflux%Cnpp)
        call comms%register_field('casaflux%Crp', casaflux%Crp)
        call comms%register_field('casaflux%Crgplant', casaflux%Crgplant)
        call comms%register_field('casaflux%Nminfix', casaflux%Nminfix)
        call comms%register_field('casaflux%Nminuptake', casaflux%Nminuptake)
        call comms%register_field('casaflux%Plabuptake', casaflux%Plabuptake)
        call comms%register_field('casaflux%Clabloss', casaflux%Clabloss)
        call comms%register_field('casaflux%fracClabile', casaflux%fracClabile)
        call comms%register_field('casaflux%fracCalloc', casaflux%fracCalloc)
        call comms%register_field('casaflux%fracNalloc', casaflux%fracNalloc)
        call comms%register_field('casaflux%fracPalloc', casaflux%fracPalloc)
        call comms%register_field('casaflux%Crmplant', casaflux%Crmplant)
        call comms%register_field('casaflux%kplant', casaflux%kplant)
        call comms%register_field('casaflux%fromPtoL', casaflux%fromPtoL)
        call comms%register_field('casaflux%Cnep', casaflux%Cnep)
        call comms%register_field('casaflux%Crsoil', casaflux%Crsoil)
        call comms%register_field('casaflux%Nmindep', casaflux%Nmindep)
        call comms%register_field('casaflux%Nminloss', casaflux%Nminloss)
        call comms%register_field('casaflux%Nminleach', casaflux%Nminleach)
        call comms%register_field('casaflux%Nupland', casaflux%Nupland)
        call comms%register_field('casaflux%Nlittermin', casaflux%Nlittermin)
        call comms%register_field('casaflux%Nsmin', casaflux%Nsmin)
        call comms%register_field('casaflux%Nsimm', casaflux%Nsimm)
        call comms%register_field('casaflux%Nsnet', casaflux%Nsnet)
        call comms%register_field('casaflux%fNminloss', casaflux%fNminloss)
        call comms%register_field('casaflux%fNminleach', casaflux%fNminleach)
        call comms%register_field('casaflux%Pdep', casaflux%Pdep)
        call comms%register_field('casaflux%Pwea', casaflux%Pwea)
        call comms%register_field('casaflux%Pleach', casaflux%Pleach)
        call comms%register_field('casaflux%Ploss', casaflux%Ploss)
        call comms%register_field('casaflux%Pupland', casaflux%Pupland)
        call comms%register_field('casaflux%Plittermin', casaflux%Plittermin)
        call comms%register_field('casaflux%Psmin', casaflux%Psmin)
        call comms%register_field('casaflux%Psimm', casaflux%Psimm)
        call comms%register_field('casaflux%Psnet', casaflux%Psnet)
        call comms%register_field('casaflux%fPleach', casaflux%fPleach)
        call comms%register_field('casaflux%kplab', casaflux%kplab)
        call comms%register_field('casaflux%kpsorb', casaflux%kpsorb)
        call comms%register_field('casaflux%kpocc', casaflux%kpocc)
        call comms%register_field('casaflux%kmlabP', casaflux%kmlabP)
        call comms%register_field('casaflux%Psorbmax', casaflux%Psorbmax)
        call comms%register_field('casaflux%frac_sapwood', casaflux%frac_sapwood)
        call comms%register_field('casaflux%sapwood_area', casaflux%sapwood_area)
        call comms%register_field('casaflux%klitter', casaflux%klitter)
        call comms%register_field('casaflux%ksoil', casaflux%ksoil)
        call comms%register_field('casaflux%fromLtoS', casaflux%fromLtoS)
        call comms%register_field('casaflux%fromStoS', casaflux%fromStoS)
        call comms%register_field('casaflux%fromLtoCO2', casaflux%fromLtoCO2)
        call comms%register_field('casaflux%fromStoCO2', casaflux%fromStoCO2)
        call comms%register_field('casaflux%fluxCtolitter', casaflux%fluxCtolitter)
        call comms%register_field('casaflux%fluxNtolitter', casaflux%fluxNtolitter)
        call comms%register_field('casaflux%fluxPtolitter', casaflux%fluxPtolitter)
        call comms%register_field('casaflux%fluxCtosoil', casaflux%fluxCtosoil)
        call comms%register_field('casaflux%fluxNtosoil', casaflux%fluxNtosoil)
        call comms%register_field('casaflux%fluxPtosoil', casaflux%fluxPtosoil)
        call comms%register_field('casaflux%fluxCtoCO2', casaflux%fluxCtoCO2)
        call comms%register_field('casamet%glai', casamet%glai)
        call comms%register_field('casamet%Tairk', casamet%Tairk)
        call comms%register_field('casamet%precip', casamet%precip)
        call comms%register_field('casamet%tsoilavg', casamet%tsoilavg)
        call comms%register_field('casamet%moistavg', casamet%moistavg)
        call comms%register_field('casamet%btran', casamet%btran)
        call comms%register_field('casamet%lnonwood', casamet%lnonwood)
        call comms%register_field('casamet%Tsoil', casamet%Tsoil)
        call comms%register_field('casamet%moist', casamet%moist)
        call comms%register_field('casamet%iveg2', casamet%iveg2)
        call comms%register_field('casamet%ijgcm', casamet%ijgcm)
        call comms%register_field('casamet%isorder', casamet%isorder)
        call comms%register_field('casamet%lat', casamet%lat)
        call comms%register_field('casamet%lon', casamet%lon)
        call comms%register_field('casamet%areacell', casamet%areacell)
        call comms%register_field('casabal%FCgppyear', casabal%FCgppyear)
        call comms%register_field('casabal%FCnppyear', casabal%FCnppyear)
        call comms%register_field('casabal%FCrmleafyear', casabal%FCrmleafyear)
        call comms%register_field('casabal%FCrmwoodyear', casabal%FCrmwoodyear)
        call comms%register_field('casabal%FCrmrootyear', casabal%FCrmrootyear)
        call comms%register_field('casabal%FCrgrowyear', casabal%FCrgrowyear)
        call comms%register_field('casabal%FCrpyear', casabal%FCrpyear)
        call comms%register_field('casabal%FCrsyear', casabal%FCrsyear)
        call comms%register_field('casabal%FCneeyear', casabal%FCneeyear)
        call comms%register_field('casabal%FNdepyear', casabal%FNdepyear)
        call comms%register_field('casabal%FNfixyear', casabal%FNfixyear)
        call comms%register_field('casabal%FNsnetyear', casabal%FNsnetyear)
        call comms%register_field('casabal%FNupyear', casabal%FNupyear)
        call comms%register_field('casabal%FNleachyear', casabal%FNleachyear)
        call comms%register_field('casabal%FNlossyear', casabal%FNlossyear)
        call comms%register_field('casabal%FPweayear', casabal%FPweayear)
        call comms%register_field('casabal%FPdustyear', casabal%FPdustyear)
        call comms%register_field('casabal%FPsnetyear', casabal%FPsnetyear)
        call comms%register_field('casabal%FPupyear', casabal%FPupyear)
        call comms%register_field('casabal%FPleachyear', casabal%FPleachyear)
        call comms%register_field('casabal%FPlossyear', casabal%FPlossyear)
        call comms%register_field('casabal%glaimon', casabal%glaimon)
        call comms%register_field('casabal%glaimonx', casabal%glaimonx)
        call comms%register_field('casabal%cplantlast', casabal%cplantlast)
        call comms%register_field('casabal%nplantlast', casabal%nplantlast)
        call comms%register_field('casabal%pplantlast', casabal%pplantlast)
        call comms%register_field('casabal%clitterlast', casabal%clitterlast)
        call comms%register_field('casabal%nlitterlast', casabal%nlitterlast)
        call comms%register_field('casabal%plitterlast', casabal%plitterlast)
        call comms%register_field('casabal%csoillast', casabal%csoillast)
        call comms%register_field('casabal%nsoillast', casabal%nsoillast)
        call comms%register_field('casabal%psoillast', casabal%psoillast)
        call comms%register_field('casabal%nsoilminlast', casabal%nsoilminlast)
        call comms%register_field('casabal%psoillablast', casabal%psoillablast)
        call comms%register_field('casabal%psoilsorblast', casabal%psoilsorblast)
        call comms%register_field('casabal%psoilocclast', casabal%psoilocclast)
        call comms%register_field('casabal%cbalance', casabal%cbalance)
        call comms%register_field('casabal%nbalance', casabal%nbalance)
        call comms%register_field('casabal%pbalance', casabal%pbalance)
        call comms%register_field('casabal%sumcbal', casabal%sumcbal)
        call comms%register_field('casabal%sumnbal', casabal%sumnbal)
        call comms%register_field('casabal%sumpbal', casabal%sumpbal)
        call comms%register_field('casabal%clabilelast', casabal%clabilelast)
        call comms%register_field('phen%phase', phen%phase)
        call comms%register_field('phen%TKshed', phen%TKshed)
        call comms%register_field('phen%doyphase', phen%doyphase)
        call comms%register_field('phen%phen', phen%phen)
        call comms%register_field('phen%aphen', phen%aphen)
        call comms%register_field('phen%phasespin', phen%phasespin)
        call comms%register_field('phen%doyphasespin_1', phen%doyphasespin_1)
        call comms%register_field('phen%doyphasespin_2', phen%doyphasespin_2)
        call comms%register_field('phen%doyphasespin_3', phen%doyphasespin_3)
        call comms%register_field('phen%doyphasespin_4', phen%doyphasespin_4)

        call comms%scatter()
        call comms%free()
    end subroutine

    SUBROUTINE climate_types (comm, climate, climate_comm, decomp)
        USE cable_def_types_mod, ONLY: climate_type, mp
        use cable_mpicommon, only: lpdecomp_t
        use mpi_f08
        USE cable_climate_mod, ONLY: climate_init,  READ_CLIMATE_RESTART_NC
        USE cable_common_module, ONLY: CABLE_USER

        INTEGER, INTENT(IN) :: comm  ! MPI communicator
        type(lpdecomp_t), optional, intent(in) :: decomp(:)
        TYPE(climate_type), intent(inout):: climate
        type(comms_t), intent(out) :: climate_comm
        integer :: rank

        call climate_init(climate, mp)
        call mpi_comm_rank(MPI_Comm(comm), rank)
        if (rank == 0) then
            if (cable_user%call_climate .AND.(.NOT.cable_user%climate_fromzero)) &
                CALL READ_CLIMATE_RESTART_NC (climate)
        end if

        call climate_comm%init(comm, decomp)
        call climate_comm%register_field('climate%mtemp_min_20', climate%mtemp_min_20)
        call climate_comm%register_field('climate%mtemp_max_20', climate%mtemp_max_20)
        call climate_comm%register_field('climate%alpha_PT_20', climate%alpha_PT_20)
        call climate_comm%register_field('climate%dtemp_31', climate%dtemp_31)
        call climate_comm%register_field('climate%dtemp_91', climate%dtemp_91)
        call climate_comm%register_field('climate%dmoist_31', climate%dmoist_31)
        call climate_comm%register_field('climate%chilldays', climate%chilldays)
        call climate_comm%register_field('climate%iveg', climate%iveg)
        call climate_comm%register_field('climate%biome', climate%biome)
        call climate_comm%register_field('climate%dtemp', climate%dtemp)
        call climate_comm%register_field('climate%dmoist', climate%dmoist)
        call climate_comm%register_field('climate%mtemp', climate%mtemp)
        call climate_comm%register_field('climate%qtemp', climate%qtemp)
        call climate_comm%register_field('climate%mmoist', climate%mmoist)
        call climate_comm%register_field('climate%mtemp_min', climate%mtemp_min)
        call climate_comm%register_field('climate%mtemp_max', climate%mtemp_max)
        call climate_comm%register_field('climate%qtemp_max', climate%qtemp_max)
        call climate_comm%register_field('climate%qtemp_max_last_year', climate%qtemp_max_last_year)
        call climate_comm%register_field('climate%mtemp_min20', climate%mtemp_min20)
        call climate_comm%register_field('climate%mtemp_max20', climate%mtemp_max20)
        call climate_comm%register_field('climate%atemp_mean', climate%atemp_mean)
        call climate_comm%register_field('climate%agdd5', climate%agdd5)
        call climate_comm%register_field('climate%gdd5', climate%gdd5)
        call climate_comm%register_field('climate%agdd0', climate%agdd0)
        call climate_comm%register_field('climate%gdd0', climate%gdd0)
        call climate_comm%register_field('climate%alpha_PT', climate%alpha_PT)
        call climate_comm%register_field('climate%evap_PT', climate%evap_PT)
        call climate_comm%register_field('climate%aevap', climate%aevap)

        call climate_comm%scatter()
        call MPI_Barrier(MPI_Comm(comm))
    end subroutine

    subroutine restart_types(comm, canopy, air, restart_comm, decomp)
        USE cable_def_types_mod
        use cable_mpicommon, only: lpdecomp_t

        INTEGER, INTENT(IN) :: comm  ! MPI communicator
        type(lpdecomp_t), optional, intent(in) :: decomp(:)
        type(comms_t), intent(out) :: restart_comm
        TYPE(canopy_type), INTENT(INOUT) :: canopy
        TYPE (air_type),INTENT(INOUT)     :: air

        call restart_comm%init(comm, decomp)

        call restart_comm%register_field('canopy%evapfbl', canopy%evapfbl)
        call restart_comm%register_field('canopy%cduv', canopy%cduv)
        call restart_comm%register_field('canopy%dewmm', canopy%dewmm)
        call restart_comm%register_field('canopy%dgdtg', canopy%dgdtg)
        call restart_comm%register_field('canopy%frpw', canopy%frpw)
        call restart_comm%register_field('canopy%frpr', canopy%frpr)
        call restart_comm%register_field('canopy%fnv', canopy%fnv)
        call restart_comm%register_field('air%rho', air%rho)
        call restart_comm%register_field('air%volm', air%volm)
        call restart_comm%register_field('air%qsat', air%qsat)
        call restart_comm%register_field('air%epsi', air%epsi)
        call restart_comm%register_field('air%visc', air%visc)
        call restart_comm%register_field('air%psyc', air%psyc)
        call restart_comm%register_field('air%dsatdk', air%dsatdk)
        call restart_comm%register_field('air%cmolar', air%cmolar)

    end subroutine
end module
