land_albedo,            & 
alb_surft,              &
mp,                     &
nrb,                    &
row_length,             &
rows,                   &
land_pts,               &
ntiles,                 &
sm_levels,              &
tile_pts,               &
tile_index,             &
land_index,             &
tile_frac,              &
L_tile_pts,             &
EffSurfRefl_dif,        &
EffSurfRefl_beam,       &
snow_flag_cable,        &
SnowFlag_3L             & 


