#!/bin/ksh
set -x 

tput reset
cwd=`pwd`

#cd ../CABLE-JULES/JULES/

#./build.ksh

#cd .tmp/
#/bin/cp *.o ../../../../JULES/JULES-CABLE/
#/bin/cp *.mod ../../../../JULES/JULES-CABLE/mods

#cd $cwd

NCDF_ROOT="/apps/netcdf/3.6.3/" 
NCDF_LIB=$NCDF_ROOT"lib/Intel" 
NCDF_INCLUDE=$NCDF_ROOT"include/Intel"

if [[ $1 == "clean" ]]; then
   #make COMPILER=intel BUILD=run CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include clean 
   make COMPILER=intel BUILD=run CDF_LIB_PATH=$NCDF_LIB CDF_MOD_PATH=$NCDF_INCLUDE clean
   #make clean 
exit
fi
 
#make 
if [[ $1 == "debug" ]]; then
   ar r libjules_debug.a *.o
   rm -f cable*
   #make COMPILER=intel BUILD=debug CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include
   make COMPILER=intel BUILD=debug CDF_LIB_PATH=$NCDF_LIB CDF_MOD_PATH=$NCDF_INCLUDE JULESDIR=$cwd
   #make BUILD=debug 
   /bin/cp jules_debug.exe examples/point*CABLE/
else
#   ar r libjules.a *.o
#   rm -f cable*
   #make COMPILER=intel BUILD=run CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include
   #make #COMPILER=intel BUILD=run CDF_LIB_PATH=$NCDF_LIB CDF_MOD_PATH=$NCDF_INCLUDE JULESDIR=$cwd
   fcm make --config-file etc/fcm-make/make-local.cfg
   #make BUILD=run
#   /bin/cp jules.exe examples/point*CABLE/
fi
   

