#!/bin/ksh
#set -x 

tput reset
cwd=`pwd`
cd ../CABLE-JULES_4calls/JULES/

./build.ksh

cd .tmp/
/bin/cp *.o ../../../End_April_cpl/
/bin/cp *.o ../../../End_April_cpl/mods

cd $cwd

if [[ $1 == "clean" ]]; then
   #make COMPILER=intel BUILD=run CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include clean 
   make clean 
exit
fi
 
#make 
if [[ $1 == "debug" ]]; then
   ar r libjules_debug.a *.o
   rm -f cable*
   #make COMPILER=intel BUILD=debug CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include
   make BUILD=debug 
   /bin/cp jules_debug.exe examples/point*CABLE/
else
   ar r libjules.a *.o
   rm -f cable*
   #make COMPILER=intel BUILD=run CDF_LIB_PATH=/usr/local/lib CDF_MOD_PATH=/usr/local/include
   make BUILD=run
   /bin/cp jules.exe examples/point*CABLE/
fi
   

