#!/bin/bash
#PBS -l ncpus=16
#PBS -l mem=6gb
#PBS -l walltime=00:30:00
#PBS -P dt6
#PBS -q normal
#PBS -l wd

module load openmpi
#module load ipm
#export IPM_LOGDIR=/short/$PROJECT/$USER/cable-dev/offline/ipm_logs
#export IPM_LOGFILE=$PBS_JOBID.$USER.$PROJECT.`date +%s`

ulimit -s unlimited
yr=1986
while [ $yr -le 1995 ]
do
  cp namelistDir/cable.nml_gswp${yr} cable.nml
  ## cp namelistDir/icycle1/cable.nml_gswp${yr} cable.nml
  #mpirun -np 16 ./cable-mpi
  mpirun -np 16 ./cable-mpi
  ###!!! mpirun -np  8 ./cable-mpi   #  8 CPUs
  ###!!! mpirun -np 16 ./cable-mpi   # 16 CPUs
  ###!!! mpirun -np 24 ./cable-mpi   # 24 CPUs
  cp out_cable.nc      out_gswp/out_gswp${yr}.nc
  cp log_cable.txt     out_gswp/log_gswp${yr}.txt
  cp -p restart_out.nc out_gswp/restart_gswp${yr}.nc
  mv restart_out.nc    restart_in_gswp.nc
  yr=`expr $yr + 1`
done

