#!/bin/csh
#input args stored by csh in $argv. $#argv = length(argv)
if ( $#argv == 2 ) then
   if ( $1 == 'um' ) then
      grep -i $2 UM/src/* core/src/common/* core/src/science/*  
   endif
   
   if ( $1 == 'offline' ) then
      grep -i $2 offline/src/* core/src/common/* core/src/science/*  
   endif
   
   if ( $1 == 'mk3l' ) then
      grep -i $2 Mk3L/src/* core/src/common/* core/src/science/*  
   endif

   if ( $1 == 'all' ) then
      grep -i $2 UM/src/*   
      grep -i $2 offline/src/* 
      grep -i $2 Mk3L/src/* core/src/common/* core/src/science/*  
   endif
   
endif

if ( $#argv == 3 ) then
   if ( $1 == 'um' ) then
      grep -i $2 UM/src/* core/src/common/* core/src/science/* | grep -i $3
   endif
   
   if ( $1 == 'offline' ) then
      grep -i $2 offline/src/* core/src/common/* core/src/science/* | grep -i $3
   endif
   
   if ( $1 == 'mk3l' ) then
      grep -i $2 Mk3L/src/* core/src/common/* core/src/science/* | grep -i $3
   endif

   if ( $1 == 'all' ) then
      grep -i $2 UM/src/* | grep -i $3
      grep -i $2 offline/src/* | grep -i $3
      grep -i $2 Mk3L/src/* core/src/common/* core/src/science/* | grep -i $3
   endif

endif



